version: '3.3'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'snail'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '7L9oiH#FGH?6oaK9'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '9esFQ@p@NAs3@!pY'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - snail-db:/var/lib/mysql

  app:
    depends_on:
      - db
    build: ./src/api
    restart: on-failure
    env_file: ./.env
    ports:
      - 8080:8080
      # - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    # environment:
    #   # SPRING_APPLICATION_JSON: '{
    #   #   "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
    #   #   "spring.datasource.username" : "$MYSQLDB_USER",
    #   #   "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
    #   #   "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    #   #   "spring.jpa.hibernate.ddl-auto" : "update"
    #   # }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
# Names our volume
volumes:
  snail-db:
