version: '3.3'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'snail'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '7L9oiH#FGH?6oaK9'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '9esFQ@p@NAs3@!pY'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - snail-db:/var/lib/mysql
# Names our volume
volumes:
  snail-db:
